### PR TITLE
add get and set syntax preference when defining computed properties

### PR DESCRIPTION
**Pull request by hjbuchanan**
## Changes proposed in this pull request
See diff

### CODE REVIEW

**Review by shyshy — APPROVED** [review]
:+1: but I was one of the biased ppl pushing for `get / set` so would be nice to get a more unanimous decision.

**Comment by hjbuchanan** [comment]
@shyshy putting it in a card for ember fireside!

**Comment by istateside** [comment]
I already forgot where we landed on this. use get/set only when you need a getter and a setter, and use the function syntax if you only need a getter? was that right?

**Comment by snackzone** [comment]
Yeah that's right.

**Comment by shyshy** [comment]
If I remember correctly, the reasoning was sorta roundabout, but, it made sense:

We should avoid using `set` on computed properties to begin with, making the benefits of splitting out `get / set` kinda moot. Most devs only used `get / set`if they needed a setter.

**Comment by istateside** [comment]
I'll type something up to clarify on this branch

**Pull request merged**
